name: Build

on:
  push:
    paths:
      - '**.kt'
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 9

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: githubBuild
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
